<?xml version="1.0" encoding="utf-8"?><Database Name="TouchSecurity" Class="VistasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=TouchSecurity.mssql.somee.com;Initial Catalog=TouchSecurity;User ID=jeangr20_SQLLogin_1;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TouchSecurityConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EmpresasMasReportes" Member="EmpresasMasReportes">
    <Type Name="EmpresasMasReportes">
      <Column Name="Empresa_Nom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Reportes" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NumeroEmpresas" Member="NumeroEmpresas">
    <Type Name="NumeroEmpresas">
      <Column Name="NUMERO_EMPRESAS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportesPorMes" Member="ReportesPorMes">
    <Type Name="ReportesPorMes">
      <Column Name="Mes" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Reportes" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportesUltimoMes" Member="ReportesUltimoMes">
    <Type Name="ReportesUltimoMes">
      <Column Name="REPORTES" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TotalReportes" Member="TotalReportes">
    <Type Name="TotalReportes">
      <Column Name="TOTAL" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UltimoReporte" Member="UltimoReporte">
    <Type Name="UltimoReporte">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Empresa_Per" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportesPorCiudad" Member="ReportesPorCiudad">
    <Type Name="ReportesPorCiudad">
      <Column Name="Empresa_Nom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Reportes" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>